server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  name: "${serverName:AuthCenter}"
  version: "${serverVersion:1.0.0}"
data:
  database:
    driver: mysql
    source: "${mysqlConnection:appuser:apppass@tcp(127.0.0.1:3306)/appdb?parseTime=True&loc=Local}"
  redis:
    addr: "${redisUrl:localhost:6379}"
    password: "${redisPass}"
    db: ${redisDB:0}
    prefix_key: "${redisBaseKey:AuthCenter}"
  mongodb:
    uri: "${mongoUrl:mongodb://localhost:27017/}"
    username: "${mongoUser:appuser}"
    password: "${mongoPass:apppass}"
    database: "${mongoDB:appdb}"
    auth_source: "${mongoAuthSource:appdb}"
    connect_timeout: 10s
    limitations:
      user:
        # per user per client (KB)
        official_mem_limit: ${mongoUserOfficialMemLimit:16}
        oauth2_mem_limit: ${mongoUserOAuthMemLimit:4096}
jwt:
  key:
    private_key: "${privateKey:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRQ1RRRmpjZnRhYmVnOE8KTXZuK0E0NzllUTcvKzFlZ0s1Tjl4UXJneTZzaFRmTFhHRzJFSm5hWktqYzNuZTJjWExvMjRDWmlvVVdqUTlqVQpWb002TUdTUnRSa293L2ZLZXJVTkoza0VDa2JTSVNoTGdWNUdtS1JqYzZrTURFYUpSbUtYNGx4YktOWGt4VUowCmNrMXcxT1FLQ2cvWEhXczdjRzZmaFVISTJYOGpwTXFJb1lpR1FwYW91OEN1LzZzeXNkd25tNy8vTkU3UVJXeGwKWDFuaHRHem9rY0VyRzdrL0dCQk5xWmVnSWxjWWpLN09rbGVZUDBzMmYxdjFsN25sRnZ0WVZPakw4SmdBYmVrUAp3VEJLL254UmJVRklXUENqZUpiUnRsQ05zeFJYTUtRd0p1eG1xbkdPZlRKdGVHSkpKSXpYbkEwKy9CVHhXL09kCnRYcVNMMjdaQWdNQkFBRUNnZ0VBSUFjU2JOOGZzWkNDWHMzQ3B6ZkI3YXJia3R6cHlicEFxYzNtV0Ura1NLbXEKSkpPNUdsRzlZUUlZSVg0MXRObE1YV3d5blNoRHU4ZWhqVW5GNEMydmFpdlFMWmcyT0xHbzJKUVowOEdpZHNqawplVXZKcENSR09TVnFndWJXbnJ3UzdNTTg0RTBJL09uVTB2d2JrT3VWTUFQUlB6STBaU2pHdnVhZWtOK1Jza0FzCm01VWs3a0xFYk8ycXRzZE9DdE9CcU5NVGxVWkpLS1dhTWNMc0ppNGNGdVMvR1RCZEY3SmJUUWl2TUMwclg3aEkKbTdISEJOSzc3TWdnYytjTjlkTCtmSE5JV0Ezd01hKzc2R1VYQmV5Uk9XdkxVY05rd0dPRGpnM0pzVVFIaWRubwpoYmNWbXlTNjY5OVhxU0lTRXpkT1I5aVNIZGpmcGtPNlpWdXVhQ1pZNndLQmdRREd1c2V3azkvOE9GQkVOMThVCklGemlLcGFxZ0xzRnIzenQvMFVZS3VjTUc1TG0vSE1lbkl0NTZoZGVKWm9vNnJYQU11b1ZtRUdlbmhoYlhpbjIKclByU3lNWmRJMDhGUjhBQzZ6TTdGdGNGb1hmd2lJRVZhUjBGZmFoT3QvRTB3blRqQkZrbmoycEs2S01VTUI1NwpGRlJrbTBiMzg4NlJDcS9BUVFvaWxiMC9vd0tCZ1FDOXI4WVBxc1RtVzdxcWV0ZDN3ZCtvZE5sQmowazF3RkhFCm56WDZkOG1nK0JVcXNkZXlkUEZOakZrUXRHWXhEZldIV2czZ1dFUFljVWxFUGxMb01NR3FUS0I3UmhvSHdDU0UKb1hxaW1aWVpUdmdUcTBJUktka3ZRcnhneEQ0NkJwOTJTYStncGh1cVpSOUhVQml5eVgvemhjZUMyd0VxT21SUQozaEsvalJYUFV3S0JnUUN6OXkraFM3amFPdEVOaGF0WG1ac2p3WGVodm1RZldQVmt2ZmYvVTlMYVZ4b29qZE5lCmxGdUdzeVFvUVJzakZMSTA5S2FobWJsTEFGYUVYM2pYQjMwNVoxS2p3N2JxekRncExIKy9jZ2FVOWMyZENMRUYKQjZTZGRWYjJ1b0wzeVdWNnRGUmNpL2F4RVkybFdaSXcyWTgzY0pyTExvSVJQVUU5ZEdqT094WWZ5d0tCZ1FDNgpUbGQ1Y2QvODVhR2M2aFNSY21GcmdvRVVyRmhhcSs5ajhJQkM1cjZxRktBdGxBbG9KUVlRaGNYQTYzN250Vzh2CnB0cTBPOTAvVEYySzRxL3BrR0hYRTNZWVBnMDVDWmFVa2tueVJHbXhwK2R1NGlsODFCNldGYlVTVWcxUVRzcjIKa244bWlaL29wM09tUmx4TDFpK1BEeG1iUStHTUNWZ1lPVll1djdMcE13S0JnUUN2c3JyVEJ6UDIxaDVKdjBKRwpiWWVVZVppcnJNaHREc21PdHNaQyt6aFBzeHRnUVBuckJhcFBUM1RrMWxNd0ZNMkhWaW1EZUwvVHlvQmllNEJBCk5GZEo4UGQzMFIwMkxOVDdFWWVTQ3FOQ09LTGx1RmVmNGllMWYzQjZSdHlVWGFxWlBmS3hra0xFVEc1bWJjelgKQmI5aVJyU0Rjdm1lcThsRzJpU3lIY3ZrVEE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t}"
    public_key: "${publicKey:LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFrMEJZM0g3V20zb1BEakw1L2dPTwovWGtPLy90WG9DdVRmY1VLNE11cklVM3kxeGh0aENaMm1TbzNONTN0bkZ5Nk51QW1ZcUZGbzBQWTFGYURPakJrCmtiVVpLTVAzeW5xMURTZDVCQXBHMGlFb1M0RmVScGlrWTNPcERBeEdpVVppbCtKY1d5alY1TVZDZEhKTmNOVGsKQ2dvUDF4MXJPM0J1bjRWQnlObC9JNlRLaUtHSWhrS1dxTHZBcnYrck1ySGNKNXUvL3pSTzBFVnNaVjlaNGJScwo2SkhCS3h1NVB4Z1FUYW1Yb0NKWEdJeXV6cEpYbUQ5TE5uOWI5WmU1NVJiN1dGVG95L0NZQUczcEQ4RXdTdjU4ClVXMUJTRmp3bzNpVzBiWlFqYk1VVnpDa01DYnNacXB4am4weWJYaGlTU1NNMTV3TlB2d1U4VnZ6bmJWNmtpOXUKMlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t}"
  salt: "${jwtSalt}"
  access_token_life_span: ${accessTokenLifeSpan:3600}
  refresh_token_life_span: ${refreshTokenLifeSpan:604800}
  issuer: "${jwtIssuer:https://tokenteam.net}"
mail:
  host: "smtp-mail.outlook.com"
  port: 587
  username: "no-reply@tokenteam.net"
  password: "${mailPassword:test}"